# FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
# WORKDIR /source

# # copy csproj and restore as distinct layers
# COPY *.sln .
# COPY aspnetapp/*.csproj ./aspnetapp/
# RUN dotnet restore

# # copy everything else and build app
# COPY aspnetapp/. ./aspnetapp/
# WORKDIR /source/aspnetapp

# FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

# ADD . /app

# WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim

ADD . /app

WORKDIR /app